name: Deploy Check
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test Dependencies
      run: |
        python -m pip install -r requirements.txt
        python -c "import streamlit, PIL, numpy; print('All packages installed!')"
